import { NextApiRequest, NextApiResponse } from 'next';
import { query } from '@/lib/db';
import { z } from 'zod';
import { getActiveUserId } from '@/utils/user';
import { hasCalendarMetadataColumns, hasFixedAppointmentColumns } from '@/lib/schemaMetadata';

const calendarSessionSchema = z.object({
  subjectId: z.string().uuid(),
  title: z.string().min(1).max(255),
  startTime: z.string().transform(str => new Date(str)),
  endTime: z.string().transform(str => new Date(str)),
  sessionType: z.enum(['study', 'exam', 'break', 'assignment']).default('study'),
  description: z.string().optional(),
  location: z.string().optional(),
});

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    switch (req.method) {
      case 'GET':
        return await getCalendarSessions(req, res);
      case 'POST':
        return await createCalendarSession(req, res);
      case 'DELETE':
        return await deleteCalendarSession(req, res);
      default:
        res.setHeader('Allow', ['GET', 'POST', 'DELETE']);
        return res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error) {
    console.error('Calendar API error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
}

async function getCalendarSessions(req: NextApiRequest, res: NextApiResponse) {
  const { userId, startDate, endDate, month, year } = req.query;

  // Use configured user id until authentication is implemented
  const userIdToUse = (userId as string) || getActiveUserId();

  let calendarDateFilter = '';
  let learningDateFilter = '';
  const params: any[] = [userIdToUse];

  if (startDate && endDate) {
    calendarDateFilter = 'AND DATE(cs.start_time) BETWEEN $2 AND $3';
    learningDateFilter = 'AND ls.date BETWEEN $2 AND $3';
    params.push(startDate, endDate);
  } else if (month && year) {
    // Filter by month and year
    calendarDateFilter = 'AND EXTRACT(MONTH FROM cs.start_time) = $2 AND EXTRACT(YEAR FROM cs.start_time) = $3';
    learningDateFilter = 'AND EXTRACT(MONTH FROM DATE(ls.date)) = $2 AND EXTRACT(YEAR FROM DATE(ls.date)) = $3';
    params.push(parseInt(month as string), parseInt(year as string));
  }

  const hasMetadata = await hasCalendarMetadataColumns();
  const hasFixed = await hasFixedAppointmentColumns();

  const calendarMetadataSelect = hasMetadata
    ? `
      cs.is_auto_generated as "isAutoGenerated",
      cs.source_subject_exam_id as "sourceSubjectExamId",
      cs.scheduling_priority as "schedulingPriority",
      ${hasFixed ? 'cs.is_fixed' : 'false'} as "isFixed",
      ${hasFixed ? 'cs.fixed_source' : "NULL"} as "fixedSource",
    `
    : `
      false as "isAutoGenerated",
      NULL::uuid as "sourceSubjectExamId",
      0 as "schedulingPriority",
      false as "isFixed",
      NULL as "fixedSource",
    `;

  const calendarSessionsResult = await query(
    `SELECT
        cs.id,
        cs.title,
        cs.start_time as "startTime",
        cs.end_time as "endTime",
        cs.planned_duration as duration,
        cs.planned_duration as "plannedDuration",
        cs.actual_duration as "actualDuration",
        cs.session_type as "sessionType",
        cs.completed,
        cs.description,
        cs.location,
        COALESCE(cs.is_all_day, false) as "isAllDay",
        ${calendarMetadataSelect}
        cs.created_at as "createdAt",
        cs.updated_at as "updatedAt",
        s.id as "subjectId",
        s.name as "subjectName",
        s.color as "subjectColor",
        'calendar' as "source"
      FROM calendar_sessions cs
      JOIN subjects s ON cs.subject_id = s.id
      WHERE cs.user_id = $1 ${calendarDateFilter}

      UNION ALL

      SELECT
        ls.id,
        CONCAT(s.name, ' Session') as title,
        ls.created_at - INTERVAL '1 minute' * ls.actual_duration as "startTime",
        ls.created_at as "endTime",
        ls.actual_duration as duration,
        ls.planned_duration as "plannedDuration",
        ls.actual_duration as "actualDuration",
        'study' as "sessionType",
        ls.completed,
        ls.notes as description,
        NULL as location,
        false as "isAllDay",
        false as "isAutoGenerated",
        NULL::uuid as "sourceSubjectExamId",
        0 as "schedulingPriority",
        false as "isFixed",
        NULL as "fixedSource",
        ls.created_at as "createdAt",
        ls.created_at as "updatedAt",
        s.id as "subjectId",
        s.name as "subjectName",
        s.color as "subjectColor",
        'learning' as "source"
      FROM learning_sessions ls
      JOIN subjects s ON ls.subject_id = s.id
      WHERE ls.user_id = $1 ${learningDateFilter}

      ORDER BY "startTime" ASC`,
    params
  );

  const result = calendarSessionsResult;

  // Convert dates
  const sessions = result.rows.map(session => ({
    ...session,
    startTime: session.startTime?.toISOString(),
    endTime: session.endTime?.toISOString(),
    createdAt: session.createdAt?.toISOString(),
    updatedAt: session.updatedAt?.toISOString(),
  }));

  return res.status(200).json(sessions);
}

async function createCalendarSession(req: NextApiRequest, res: NextApiResponse) {
  const validation = calendarSessionSchema.safeParse(req.body);
  
  if (!validation.success) {
    return res.status(400).json({ 
      error: 'Validation failed',
      details: validation.error.issues 
    });
  }

  const data = validation.data;
  const userId = req.body.userId || getActiveUserId();

  // Validate that start time is before end time
  if (data.startTime >= data.endTime) {
    return res.status(400).json({ error: 'Start time must be before end time' });
  }

  // Calculate duration in minutes
  const duration = Math.round((data.endTime.getTime() - data.startTime.getTime()) / (1000 * 60));

  // Verify subject exists and belongs to user
  const subjectCheck = await query(
    'SELECT id FROM subjects WHERE id = $1 AND user_id = $2',
    [data.subjectId, userId]
  );

  if (subjectCheck.rows.length === 0) {
    return res.status(400).json({ error: 'Subject not found or does not belong to user' });
  }

  const result = await query(`
    INSERT INTO calendar_sessions (
      user_id, subject_id, title, start_time, end_time, planned_duration,
      session_type, description, location
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING
      id,
      title,
      start_time as "startTime",
      end_time as "endTime",
      planned_duration as duration,
      planned_duration as "plannedDuration",
      actual_duration as "actualDuration",
      session_type as "sessionType",
      completed,
      description,
      location,
      created_at as "createdAt",
      updated_at as "updatedAt"
  `, [
    userId,
    data.subjectId,
    data.title,
    data.startTime,
    data.endTime,
    duration,
    data.sessionType,
    data.description || null,
    data.location || null
  ]);

  const session = result.rows[0];

  // Get subject information for response
  const subjectInfo = await query(
    'SELECT id as "subjectId", name as "subjectName", color as "subjectColor" FROM subjects WHERE id = $1',
    [data.subjectId]
  );

  const responseSession = {
    ...session,
    ...subjectInfo.rows[0],
    startTime: session.startTime?.toISOString(),
    endTime: session.endTime?.toISOString(),
    createdAt: session.createdAt?.toISOString(),
    updatedAt: session.updatedAt?.toISOString(),
  };

  return res.status(201).json(responseSession);
}

async function deleteCalendarSession(req: NextApiRequest, res: NextApiResponse) {
  const { sessionId } = req.query;
  const userId = req.body?.userId || getActiveUserId();

  if (!sessionId || typeof sessionId !== 'string') {
    return res.status(400).json({ error: 'Session ID is required' });
  }

  // Verify session exists and belongs to user
  const sessionCheck = await query(
    'SELECT id FROM calendar_sessions WHERE id = $1 AND user_id = $2',
    [sessionId, userId]
  );

  if (sessionCheck.rows.length === 0) {
    return res.status(404).json({ error: 'Session not found or does not belong to user' });
  }

  // Prevent deletion of fixed appointments (terminplan)
  if (await hasFixedAppointmentColumns()) {
    const fixedCheck = await query('SELECT is_fixed FROM calendar_sessions WHERE id = $1', [sessionId]);
    if (fixedCheck.rows.length > 0 && fixedCheck.rows[0].is_fixed) {
      return res.status(409).json({ error: 'Cannot delete fixed appointment (terminplan)' });
    }
  }

  // Delete the session
  await query('DELETE FROM calendar_sessions WHERE id = $1', [sessionId]);

  return res.status(200).json({ message: 'Session deleted successfully', sessionId });
}
