import { useState, useCallback, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { apiFetch } from '@/lib/apiClient';
import { CalendarSession } from '../types/calendar';

export interface UseCalendarSessionsReturn {
  sessions: CalendarSession[];
  loading: boolean;
  error: string | null;
  fetchSessionsForMonth: (year: number, month: number) => Promise<void>;
  fetchSessionsForDateRange: (startDate: Date, endDate: Date) => Promise<void>;
  getSessionsForDate: (date: Date) => CalendarSession[];
  createSession: (sessionData: Omit<CalendarSession, 'id' | 'createdAt' | 'updatedAt'>) => Promise<CalendarSession>;
  updateSession: (sessionId: string, updates: Partial<CalendarSession>) => Promise<boolean>;
  deleteSession: (sessionId: string) => Promise<boolean>;
  refreshSessions: () => Promise<void>;
  syncFromSubjects: () => Promise<void>;
  // Enhanced integration helpers
  userSessions?: CalendarSession[];
  terminplanSessions?: CalendarSession[];
  allSessions?: CalendarSession[];
  showTerminplanEvents?: boolean;
  setShowTerminplanEvents?: (show: boolean) => void;
  importTerminplan?: () => Promise<{ added: number; updated: number; removed: number } | null>;
  isTerminplanImported?: boolean;
}

export const useCalendarSessions = (): UseCalendarSessionsReturn => {
  const sessionData = useSession();
  const session = sessionData?.data;
  const userId = session?.sub;
  const [sessions, setSessions] = useState<CalendarSession[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showTerminplanEvents, setShowTerminplanEvents] = useState(true);
  const [isTerminplanImported, setIsTerminplanImported] = useState(false);

  // Fetch sessions for a specific month
  const fetchSessionsForMonth = useCallback(async (year: number, month: number) => {
    if (!userId) {
      setSessions([]);
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const response = await apiFetch(`/api/calendar?userId=${userId}&year=${year}&month=${month}`);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch calendar sessions: ${response.statusText}`);
      }

      const data = await response.json();
      
      // Convert date strings back to Date objects
      const sessionsWithDates = data.map((session: any) => ({
        ...session,
        startTime: new Date(session.startTime),
        endTime: new Date(session.endTime),
        origin: session.isAutoGenerated ? 'auto' : session.origin ?? 'manual'
      }));

      setSessions(sessionsWithDates);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to load calendar sessions';
      console.error('Failed to fetch calendar sessions:', err);
      setError(errorMessage);
      setSessions([]);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  // Fetch sessions for a date range
  const fetchSessionsForDateRange = useCallback(async (startDate: Date, endDate: Date) => {
    if (!userId) {
      setSessions([]);
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const startDateStr = startDate.toISOString().split('T')[0];
      const endDateStr = endDate.toISOString().split('T')[0];

      const response = await apiFetch(`/api/calendar?userId=${userId}&startDate=${startDateStr}&endDate=${endDateStr}`);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch calendar sessions: ${response.statusText}`);
      }

      const data = await response.json();
      
      // Convert date strings back to Date objects
      const sessionsWithDates = data.map((session: any) => ({
        ...session,
        startTime: new Date(session.startTime),
        endTime: new Date(session.endTime),
        origin: session.isAutoGenerated ? 'auto' : session.origin ?? 'manual'
      }));

      setSessions(sessionsWithDates);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to load calendar sessions';
      console.error('Failed to fetch calendar sessions:', err);
      setError(errorMessage);
      setSessions([]);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  // Get sessions for a specific date (from loaded sessions)
  const getSessionsForDate = useCallback((date: Date): CalendarSession[] => {
    const targetDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    
    return sessions.filter(session => {
      const sessionDate = new Date(session.startTime.getFullYear(), session.startTime.getMonth(), session.startTime.getDate());
      if (sessionDate.getTime() !== targetDate.getTime()) return false;
      if (!showTerminplanEvents && (session as any).isFixed && (session as any).fixedSource === 'terminplan') return false;
      return true;
    });
  }, [sessions, showTerminplanEvents]);

  // Create new calendar session
  const createSession = useCallback(async (
    sessionData: Omit<CalendarSession, 'id' | 'createdAt' | 'updatedAt'>
  ): Promise<CalendarSession> => {
    if (!userId) {
      throw new Error('User not authenticated');
    }

    try {
      setLoading(true);
      setError(null);

      const requestBody = {
        userId,
        subjectId: sessionData.subjectId,
        title: sessionData.title,
        startTime: sessionData.startTime.toISOString(),
        endTime: sessionData.endTime.toISOString(),
        sessionType: sessionData.type,
        description: sessionData.description,
        location: sessionData.location,
      };

      const response = await apiFetch('/api/calendar', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to create session');
      }

      const rawSession = await response.json();
      
      // Convert dates and add to local state
      const sessionWithDates: CalendarSession = {
        ...rawSession,
        startTime: new Date(rawSession.startTime),
        endTime: new Date(rawSession.endTime),
        isAutoGenerated: false,
        origin: 'manual',
        plannedDuration: rawSession.plannedDuration ?? rawSession.duration,
        duration: rawSession.duration ?? rawSession.plannedDuration,
      };

      setSessions(prev => [...prev, sessionWithDates]);
      return sessionWithDates;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to create session';
      setError(errorMessage);
      throw err;
    } finally {
      setLoading(false);
    }
  }, [userId]);

  // Refresh current sessions
  const refreshSessions = useCallback(async () => {
    // Reload current month's sessions
    const now = new Date();
    await fetchSessionsForMonth(now.getFullYear(), now.getMonth() + 1);
  }, [fetchSessionsForMonth]);

  // Force refresh when subjects are updated (for external sync)
  const syncFromSubjects = useCallback(async () => {
    if (!userId) {
      return;
    }

    try {
      setLoading(true);
      setError(null);

      // First trigger backend sync
      const syncResponse = await apiFetch('/api/calendar/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId })
      });
      
      if (!syncResponse.ok) {
        throw new Error('Failed to sync calendar');
      }
      
      // Then refresh local data
      await refreshSessions();
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to sync calendar';
      setError(errorMessage);
      console.error('Calendar sync error:', err);
    } finally {
      setLoading(false);
    }
  }, [refreshSessions, userId]);

  // Update a calendar session
  const updateSession = useCallback(async (sessionId: string, updates: Partial<CalendarSession>): Promise<boolean> => {
    try {
      setError(null);

      // Determine the source of the session to route the update correctly
      const targetSession = sessions.find(s => s.id === sessionId);
      const source = targetSession?.source ?? 'calendar';

      // Normalize common update fields
      const normalized: any = {};
      if (updates.completed !== undefined) normalized.completed = updates.completed;
      if (updates.duration !== undefined) normalized.duration = Math.round(updates.duration);
      if (updates.description !== undefined) normalized.description = updates.description;
      if (updates.title !== undefined) normalized.title = updates.title;
      if (updates.location !== undefined) normalized.location = updates.location;
      if (updates.startTime !== undefined) normalized.startTime = updates.startTime;
      if (updates.endTime !== undefined) normalized.endTime = updates.endTime;

      if (source === 'learning') {
        // Tracker-created sessions live in learning_sessions; use its API
        const learningUpdates: any = {};
        if (normalized.completed !== undefined) learningUpdates.completed = normalized.completed;
        if (normalized.duration !== undefined) learningUpdates.duration = normalized.duration;

        const resp = await apiFetch(`/api/sessions/${sessionId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(learningUpdates),
        });

        if (!resp.ok) {
          const errorData = await resp.json().catch(() => ({ error: 'Failed to update learning session' }));
          throw new Error(errorData.error || 'Failed to update learning session');
        }

        // Update local state optimistically
        setSessions(prev => prev.map(s => (s.id === sessionId ? { ...s, ...updates } : s)));

        // Dispatch events to keep UI in sync (mirror calendar path behavior)
        window.dispatchEvent(new CustomEvent('sessionUpdated', {
          detail: {
            sessionId,
            updates: learningUpdates,
            timestamp: Date.now(),
            completionChanged: updates.completed !== undefined,
            wasCompleted: updates.completed,
          }
        }));

        if (updates.completed !== undefined) {
          const eventName = updates.completed ? 'sessionCompleted' : 'sessionIncomplete';
          const approxXP = Math.floor((updates.duration || 0) * 2);
          const xpDelta = updates.completed ? approxXP : -approxXP;
          window.dispatchEvent(new CustomEvent(eventName, {
            detail: {
              sessionId,
              completed: updates.completed,
              xpGained: updates.completed ? approxXP : 0,
              xpDelta,
              timestamp: Date.now(),
            }
          }));
        }

        return true;
      }

      // Default path: calendar sessions API
      const response = await apiFetch(`/api/calendar/${sessionId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(normalized),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Failed to update session' }));
        throw new Error(errorData.error || 'Failed to update session');
      }

      type UpdateResponse = {
        session?: CalendarSession;
        subjectExamUpdate?: { subjectId: string; examDate: string | Date };
      };

      const payload: UpdateResponse = await response.json().catch(() => ({} as UpdateResponse));

      const responseSession = payload?.session;
      const normalizedSession = responseSession
        ? {
            ...responseSession,
            startTime: responseSession.startTime ? new Date(responseSession.startTime) : updates.startTime,
            endTime: responseSession.endTime ? new Date(responseSession.endTime) : updates.endTime,
          }
        : null;

      setSessions(prev => prev.map(session => (session.id === sessionId ? { ...session, ...(normalizedSession || {}), ...updates } : session)));

      if (payload?.subjectExamUpdate?.subjectId && payload.subjectExamUpdate.examDate) {
        window.dispatchEvent(new CustomEvent('subjectExamDateChanged', {
          detail: {
            subjectId: payload.subjectExamUpdate.subjectId,
            examDate: new Date(payload.subjectExamUpdate.examDate),
          }
        }));
      }

      window.dispatchEvent(new CustomEvent('sessionUpdated', {
        detail: {
          sessionId,
          updates: normalized,
          timestamp: Date.now(),
          completionChanged: updates.completed !== undefined,
          wasCompleted: updates.completed,
        }
      }));

      // Dispatch sessionCompleted/Incomplete events for marking complete/incomplete
      // (Don't do this for duration edits - only for completion status changes)
      if (updates.completed !== undefined) {
        const eventName = updates.completed ? 'sessionCompleted' : 'sessionIncomplete';
        const approxXP = Math.floor((updates.duration || normalized.duration || 0) * 2);
        const xpDelta = updates.completed ? approxXP : -approxXP;
        window.dispatchEvent(new CustomEvent(eventName, {
          detail: {
            sessionId,
            completed: updates.completed,
            xpGained: updates.completed ? approxXP : 0,
            xpDelta,
            timestamp: Date.now(),
          }
        }));
      }

      return true;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to update session';
      setError(errorMessage);
      console.error('Update calendar session error:', err);
      return false;
    }
  }, [sessions]);

  // Delete a calendar session
  const deleteSession = useCallback(async (sessionId: string): Promise<boolean> => {
    if (!userId) {
      throw new Error('User not authenticated');
    }

    try {
      setError(null);

      const response = await apiFetch(`/api/calendar?sessionId=${sessionId}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ userId }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Failed to delete session' }));
        throw new Error(errorData.error || 'Failed to delete session');
      }

      // Remove the session from local state
      setSessions(prev => prev.filter(session => session.id !== sessionId));

      // Dispatch event for calendar refresh
      window.dispatchEvent(new CustomEvent('sessionDeleted', {
        detail: { sessionId, timestamp: Date.now() }
      }));

      return true;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to delete session';
      setError(errorMessage);
      console.error('Delete calendar session error:', err);
      return false;
    }
  }, [userId]);

  // Listen for external session updates (e.g., from SessionEditModal)
  useEffect(() => {
    const handleExternalSessionUpdate = (event: any) => {
      const { sessionId, updates } = event.detail;
      
      // Update the session in our local state
      setSessions(prevSessions => 
        prevSessions.map(session => 
          session.id === sessionId 
            ? { ...session, ...updates }
            : session
        )
      );
    };

    const handleSessionCompleted = async (event: any) => {

      const eventData = event.detail;

      // Create calendar session for the completed session if we have session data
      if (eventData.sessionData) {
        try {
          const sessionData = eventData.sessionData;
          const actualDuration = eventData.actualDuration;
          const plannedDuration = eventData.plannedDuration;

          const plannedMinutes = plannedDuration ?? actualDuration ?? 0;
          const sessionRequest: Omit<CalendarSession, 'id' | 'createdAt' | 'updatedAt'> = {
            title: `${sessionData.subjectName} Learning Session`,
            subjectId: sessionData.subjectId,
            subjectName: sessionData.subjectName,
            subjectColor: sessionData.subjectColor,
            startTime: new Date(sessionData.startTime),
            endTime: new Date(sessionData.endTime),
            plannedDuration: plannedMinutes,
            duration: plannedMinutes,
            completed: true,
            type: 'study',
            description: `Completed learning session${actualDuration !== plannedDuration ? ` (planned: ${plannedDuration}min, actual: ${actualDuration}min)` : ''}`,
            source: 'calendar'
          };

          const newSession = await createSession(sessionRequest);

          // After creating, update with actual duration if different
          if (newSession && actualDuration && actualDuration !== plannedDuration) {
            try {
              await updateSession(newSession.id, {
                actualDuration: actualDuration,
                completed: true
              });
            } catch (updateError) {
              console.warn('📅 Failed to update calendar session with actual duration:', updateError);
            }
          }

        } catch (calendarError) {
          console.error('📅 Failed to create calendar session from completed session:', calendarError);
        }
      }

      // Refresh calendar data to show any updates
      try {
        await refreshSessions();
      } catch (error) {
        console.error('📅 Failed to refresh calendar after session completion:', error);
      }
    };

    const handleSessionStarted = (event: any) => {
      // Optional: Could be used to show live session indicators
    };

    window.addEventListener('sessionUpdated', handleExternalSessionUpdate);
    window.addEventListener('sessionCompleted', handleSessionCompleted);
    window.addEventListener('sessionStarted', handleSessionStarted);

    return () => {
      window.removeEventListener('sessionUpdated', handleExternalSessionUpdate);
      window.removeEventListener('sessionCompleted', handleSessionCompleted);
      window.removeEventListener('sessionStarted', handleSessionStarted);
    };
  }, [refreshSessions]);

  // Check terminplan import status on mount
  useEffect(() => {
    const checkTerminplanStatus = async () => {
      if (!userId) return;

      try {
        const res = await apiFetch('/api/terminplan/status');
        if (res.ok) {
          const data = await res.json();
          setIsTerminplanImported(data.isImported);
        }
      } catch (error) {
        console.error('Failed to check terminplan status:', error);
      }
    };

    checkTerminplanStatus();
  }, [userId]);

  // Derived collections for integration
  const terminplanSessions = sessions.filter(s => (s as any).isFixed && (s as any).fixedSource === 'terminplan');
  const userSessionsOnly = sessions.filter(s => !((s as any).isFixed && (s as any).fixedSource === 'terminplan'));
  const allSessions = showTerminplanEvents ? sessions : userSessionsOnly;

  // Import terminplan via cron endpoint
  const importTerminplan = useCallback(async (): Promise<{ added: number; updated: number; removed: number } | null> => {
    try {
      const res = await apiFetch('/api/cron/terminplan', { method: 'POST' });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data?.error || 'Terminplan import failed');
      await refreshSessions();
      // Mark terminplan as imported
      if (data?.applied && (data.applied.added > 0 || data.applied.updated > 0)) {
        setIsTerminplanImported(true);
      }
      return data?.applied || null;
    } catch (e) {
      console.error('Terminplan import failed', e);
      setError(e instanceof Error ? e.message : 'Terminplan import failed');
      return null;
    }
  }, [refreshSessions]);

  return {
    sessions,
    loading,
    error,
    fetchSessionsForMonth,
    fetchSessionsForDateRange,
    getSessionsForDate,
    createSession,
    updateSession,
    deleteSession,
    refreshSessions,
    syncFromSubjects,
    // Enhanced
    userSessions: userSessionsOnly,
    terminplanSessions,
    allSessions,
    showTerminplanEvents,
    setShowTerminplanEvents,
    importTerminplan,
    isTerminplanImported,
  };
};

export default useCalendarSessions;
