import { createHash } from 'crypto';
import { CalendarSession } from '../types/calendar';
import { SubjectTask } from '../types/tasks';
import { Subject } from '../types';
import { buildStudySchedule } from './scheduler/intelligentSessionScheduler';

export interface CalendarEventGeneratorOptions {
  includeExams: boolean;
  includeTaskDeadlines: boolean;
  includeStudySessions: boolean;
  studySessionsWeeksAhead: number;
}

const DEFAULT_OPTIONS: CalendarEventGeneratorOptions = {
  includeExams: true,
  includeTaskDeadlines: true,
  includeStudySessions: false, // Focus only on important dates
  studySessionsWeeksAhead: 2
};

export function generateCalendarEventsFromSubjects(
  subjects: (Subject & { tasks?: SubjectTask[] })[],
  options: CalendarEventGeneratorOptions = DEFAULT_OPTIONS
): CalendarSession[] {
  const events: CalendarSession[] = [];
  const examEvents: CalendarSession[] = [];
  const taskEvents: CalendarSession[] = [];

  subjects.forEach(subject => {
    if (options.includeExams) {
      const examEvent = generateExamEvent(subject);
      if (examEvent) {
        examEvents.push(examEvent);
      }
    }

    if (options.includeTaskDeadlines && subject.tasks) {
      subject.tasks.forEach(task => {
        if (task.dueDate) {
          taskEvents.push(generateTaskDeadlineEvent(task, subject));
        }
      });
    }
  });

  events.push(...examEvents, ...taskEvents);

  if (options.includeStudySessions) {
    const baseSubjects: Subject[] = subjects.map(subject => ({
      id: subject.id,
      userId: subject.userId,
      name: subject.name,
      color: subject.color,
      startDate: subject.startDate,
      examDate: subject.examDate,
      hoursPerWeek: subject.hoursPerWeek,
      daysPerWeek: subject.daysPerWeek,
      intensityWeeks: subject.intensityWeeks,
      completedHours: subject.completedHours,
      targetHours: subject.targetHours,
    }));

    const studySessions = buildStudySchedule(baseSubjects, events);
    events.push(...studySessions);
  }

  return events.sort((a, b) => a.startTime.getTime() - b.startTime.getTime());
}

export function generateExamEvent(subject: Subject): CalendarSession | null {
  if (!subject.examDate) return null;

  const hash = createHash('sha256').update(`exam-${subject.id}`).digest('hex');
  const uuid = [
    hash.substring(0, 8),
    hash.substring(8, 12),
    hash.substring(12, 16),
    hash.substring(16, 20),
    hash.substring(20, 32)
  ].join('-');
  
  return {
    id: uuid,
    title: `${subject.name} Final Exam`,
    subjectId: subject.id,
    subjectName: subject.name,
    subjectColor: subject.color,
    startTime: new Date(subject.examDate.getTime()),
    endTime: new Date(subject.examDate.getTime() + 3 * 60 * 60 * 1000),
    plannedDuration: 180,
    duration: 180,
    completed: false,
    type: 'exam',
    description: `Final examination for ${subject.name}`,
    isAutoGenerated: true,
    sourceSubjectExamId: subject.id,
    schedulingPriority: 0,
    origin: 'auto',
    source: 'calendar',
  };
}

export function generateTaskDeadlineEvent(task: SubjectTask, subject: Subject): CalendarSession {
  const hash = createHash('sha256').update(`task-${task.id}`).digest('hex');
  const uuid = [
    hash.substring(0, 8),
    hash.substring(8, 12),
    hash.substring(12, 16),
    hash.substring(16, 20),
    hash.substring(20, 32)
  ].join('-');

  return {
    id: uuid,
    title: `${subject.name} ${task.title} Due`,
    subjectId: subject.id,
    subjectName: subject.name,
    subjectColor: subject.color,
    startTime: new Date(task.dueDate.getTime()),
    endTime: new Date(task.dueDate.getTime() + 60 * 60 * 1000),
    plannedDuration: 60,
    duration: 60,
    completed: task.status === 'completed',
    type: 'assignment',
    description: task.description || `${task.type} assignment for ${subject.name}`,
    isAutoGenerated: true,
    schedulingPriority: 10,
    origin: 'auto',
    source: 'calendar',
  };
}
